### ISSUE TITLE
Finish bindings for useQuery

### ISSUE THREAD

**Issue by fakenickels** [Astrocoders/reason-apollo-hooks#1]
- fetchMore
- refetch

**Comment by hew** [comment]
It seems like I can't make a query where I pass through options. Is that the result of the unfinished bindings, or do you think I am just doing something wrong?

**Comment by hew** [comment]
Regardless, I'll see if I can finish this up.

**Comment by fakenickels** [comment]
do you mean this param? https://github.com/Astrocoders/reason-apollo-hooks/blob/master/src/Query.re#L42

**Comment by hew** [comment]
Yeah when I provide `~options`, I can't return the `(simple, full)` tuple. But if I don't pass options, I can.

**Comment by hew** [comment]
Ah, nevermind. I had `(~options)` vs `(~options, ())`. My mistake!

**Comment by fakenickels** [comment]
oh I see!
maybe there is another way to make this more explicit for users? Point about that in the README?

**Comment by hew** [comment]
I think what I will do that might be of broader use is write a blog post on common compiler errors in reason that include this one. I think it's less a problem with this library's API design or readme, and more that the optional labeled arguments syntax is 1.) easy to forget, and 2.) isn't really pointed out that well by the compiler.

**Comment by fakenickels** [comment]
That makes sense!

**Comment by fakenickels** [comment]
https://github.com/apollographql/react-apollo/tree/master/packages/hooks#a-usequery

**Comment by idkjs** [comment]
@hew do you have a working demo with updated deps that you might share? Can't seem to use this with updated deps. Thank you, sir.

**Comment by fakenickels** [comment]
refetch bound, now just fetchMore missing

**Comment by MargaretKrutikova** [comment]
I just wanted to rewrite an app from `reason-apollo` into `reason-apollo-hooks` and need `fetchMore`, so I would be glad to help write bindings for it. Is someone already working on it? 

I was also thinking about including network status in the same change since it seems useful to distinguish between just `loading` status and `fetching more`, [`NetworkStatus`](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/networkStatus.ts) type from `apollo-client` package.

**Comment by fakenickels** [comment]
No one of us is working on it, your help here would be much appreciated!

**Comment by MargaretKrutikova** [comment]
Great! I will start working on it.
