### ISSUE TITLE
Missing cache-and-network fetchPolicy

### ISSUE THREAD

**Issue by baransu** [Astrocoders/reason-apollo-hooks#51]
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/watchQueryOptions.ts#L25

**Comment by MargaretKrutikova** [comment]
The problem here might be that the types `FetchPolicy` and `WatchQueryFetchPolicy` where intentionally split to avoid passing `cache-and-network` inside `ApolloClient#query`, see [changelog](https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md#apollo-client-260-1) for `Apollo 2.6.0`. It was fixed according to this [issue](https://github.com/apollographql/apollo-client/issues/3130).

So I might not sure it is completely safe to add it to `fetchPolicy`.

**Comment by MargaretKrutikova** [comment]
Oh, no, you are totally right. I checked the type definitions for `useQuery`, and it uses `WatchQueryFetchPolicy` ([source code](https://github.com/apollographql/react-apollo/blob/master/packages/common/src/types/types.ts#L30)), so it should be added. I am on it!
